version: "3.8"

services:
  app:
    build: ./Flask_app
    container_name: flaskapp
    # ports:
    #   - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    ports:
      - "5000:5000"
    restart: always

networks:
  default:
    driver: bridge
    
